# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77b7ba814e47c156425e5923c5c93229019ed5936ca2c8743ce39fd1b15af36cdba07f65acbaaa4b7b17f42299188ac9d5e8558c0b6d11250d6c0aa1e6764b1d

test:
  secret_key_base: cbf3d515e9ce356fd6fd2d5c07beade12918bdf70ceef8ed154493b59f1d5b03ee750a30c438ef2239db11fcb5a45b49e264c5bbb6d8fc4122804c8cb4989d99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
